package org.apache.logging.bench.jpa;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.ThreadContext;

/**
 * The JPA appender, verified by reading the rows back. Feature matrix §1.
 *
 * <p>Same shape as the db bench: logging that produces no error proves nothing,
 * because Log4j catches appender exceptions and reports them through
 * StatusLogger while the JVM still exits 0. The assertion is the row count
 * before and after.
 *
 * <p>What makes this appender different from JDBC is where the configuration
 * lives: Log4j is told only a persistence unit name and an entity class, and
 * everything about the connection comes from META-INF/persistence.xml. So a
 * connection mistake surfaces here as a Log4j appender error naming JPA, which
 * is a confusing place to start debugging unless you know the split.
 *
 * <pre>
 *   ./bench run jpa --config xml/appender-jpa
 * </pre>
 */
public final class JpaBench {

    private static final String URL = "jdbc:h2:./logs/jpa/log4jpa;AUTO_SERVER=TRUE";

    private static final Logger log = LogManager.getLogger(JpaBench.class);

    public static void main(final String[] args) throws Exception {
        System.out.println("JPA appender bench");
        System.out.println("  jdbc url   " + URL);
        System.out.println("  config     "
                + System.getProperty("log4j.configurationFile", "<default>"));
        System.out.println("  entity     " + BenchLogEntity.class.getName());
        System.out.println();

        createSchema();
        final long before = countRows();

        emit();

        // Give the appender a moment: bufferSize=0 writes per event, but the
        // provider's own flush still happens on the calling thread's commit.
        LogManager.shutdown();

        final long after = countRows();
        System.out.printf("%nBENCH_LOG_EVENTS rows: %d before, %d after (delta %d)%n",
                before, after, after - before);

        if (after > before) {
            dump();
        } else {
            System.out.println();
            System.out.println("Nothing was written. Either the active config has no JPA");
            System.out.println("appender, or the appender failed and reported it through");
            System.out.println("StatusLogger — re-run with status=\"DEBUG\" on the");
            System.out.println("Configuration element to see why.");
        }
    }

    /**
     * Creates the table before Log4j initialises.
     *
     * <p>The persistence unit asks EclipseLink to generate it, and EclipseLink
     * tries — but its H2 platform emits H2 <em>1.x</em> DDL:
     *
     * <pre>
     *   CREATE TABLE BENCH_LOG_EVENTS (ID BIGINT IDENTITY NOT NULL, ...)
     * </pre>
     *
     * and H2 2.x removed {@code IDENTITY} as a column modifier, so it fails with
     * a syntax error. EclipseLink treats DDL failures as warnings, so deployment
     * still reports success and every subsequent insert fails with
     * "Table BENCH_LOG_EVENTS not found (this database is empty)" — an error
     * that points at the table rather than at the CREATE that never worked. The
     * real message only appears in H2's own trace file, not in the log.
     *
     * <p>So the schema is created here instead, in the one place a mismatch
     * between provider and database cannot hide. The column names come from the
     * INSERT EclipseLink generates for BasicLogEventEntity's mappings; only the
     * ID column differs, using the syntax H2 2.x actually accepts.
     */
    private static void createSchema() throws Exception {
        java.nio.file.Files.createDirectories(java.nio.file.Path.of("logs", "jpa"));
        try (Connection c = DriverManager.getConnection(URL, "sa", "");
                Statement s = c.createStatement()) {
            s.execute("CREATE TABLE IF NOT EXISTS BENCH_LOG_EVENTS ("
                    + "ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "CONTEXT_MAP VARCHAR, "
                    + "CONTEXT_STACK VARCHAR, "
                    + "INSTANT VARCHAR, "
                    + "LEVEL VARCHAR, "
                    + "LOGGERFQCN VARCHAR, "
                    + "LOGGERNAME VARCHAR, "
                    + "MARKER VARCHAR, "
                    + "MESSAGE VARCHAR, "
                    + "NANOTIME BIGINT, "
                    + "SOURCE VARCHAR, "
                    + "THREADID BIGINT, "
                    + "THREADNAME VARCHAR, "
                    + "THREADPRIORITY INTEGER, "
                    + "THROWN VARCHAR, "
                    + "TIMEMILLIS BIGINT)");
            // The sequence the entity's @SequenceGenerator names. allocationSize
            // must match, or EclipseLink hands out ids the sequence has not
            // reserved and inserts collide once the pool wraps.
            s.execute("CREATE SEQUENCE IF NOT EXISTS BENCH_LOG_SEQ START WITH 1 INCREMENT BY 50");
        }
    }

    private static void emit() {
        ThreadContext.put("traceId", "jpa-bench-0001");
        ThreadContext.put("tenant", "acme-corp");
        ThreadContext.push("outer");
        try {
            log.info("A plain event");
            log.info("A parameterised event: user {} order {}", "alice", Integer.valueOf(4711));
            log.warn("A warning");
            log.error("An event with a throwable",
                    new IllegalStateException("synthetic JPA failure"));
            for (int i = 1; i <= 10; i++) {
                log.info("Bulk event {} of 10", Integer.valueOf(i));
            }
        } finally {
            ThreadContext.clearAll();
        }
    }

    private static long countRows() {
        try (Connection c = DriverManager.getConnection(URL, "sa", "");
                Statement s = c.createStatement();
                ResultSet rs = s.executeQuery("SELECT COUNT(*) FROM BENCH_LOG_EVENTS")) {
            return rs.next() ? rs.getLong(1) : 0L;
        } catch (final Exception e) {
            // createSchema() runs first, so a failure here is real — but
            // returning 0 keeps the before/after comparison meaningful rather
            // than aborting before anything has been logged.
            return 0L;
        }
    }

    private static void dump() {
        System.out.println();
        System.out.printf("  %-13s %-7s %-30s %-38s %s%n",
                "TIMEMILLIS", "LEVEL", "LOGGERNAME", "MESSAGE", "CONTEXT_MAP");
        // Column names come from BasicLogEventEntity's own mappings, not from
        // anything this app chose: TIMEMILLIS/LOGGERNAME, not EVENTDATE/LOGGER
        // as the JDBC appender's hand-written schema uses.
        final String sql = "SELECT TIMEMILLIS, LEVEL, LOGGERNAME, MESSAGE, CONTEXT_MAP "
                + "FROM BENCH_LOG_EVENTS ORDER BY ID DESC LIMIT 8";
        try (Connection c = DriverManager.getConnection(URL, "sa", "");
                Statement s = c.createStatement();
                ResultSet rs = s.executeQuery(sql)) {
            while (rs.next()) {
                System.out.printf("  %-13s %-7s %-30s %-38s %s%n",
                        String.valueOf(rs.getObject(1)),
                        rs.getString(2),
                        truncate(rs.getString(3), 29),
                        truncate(rs.getString(4), 37),
                        truncate(rs.getString(5), 40));
            }
        } catch (final Exception e) {
            // The column names come from BasicLogEventEntity's mappings, which
            // the provider may spell differently — report rather than pretend.
            System.out.println("  <could not read rows back: " + e + ">");
            describeColumns();
        }
    }

    private static void describeColumns() {
        try (Connection c = DriverManager.getConnection(URL, "sa", "");
                Statement s = c.createStatement();
                ResultSet rs = s.executeQuery(
                        "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS "
                                + "WHERE TABLE_NAME = 'BENCH_LOG_EVENTS' ORDER BY ORDINAL_POSITION")) {
            final StringBuilder columns = new StringBuilder("  columns: ");
            while (rs.next()) {
                columns.append(rs.getString(1)).append(' ');
            }
            System.out.println(columns.toString().trim());
        } catch (final Exception e) {
            System.out.println("  <could not describe the table: " + e + ">");
        }
    }

    private static String truncate(final String s, final int max) {
        if (s == null) {
            return "<null>";
        }
        return s.length() <= max ? s : s.substring(0, max - 1) + "…";
    }

    private JpaBench() {}
}
